controllers/LangController.php
<?php

namespace app\controllers;

use Yii;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\BadRequestHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * LangController implements the CRUD actions for Status model.
 */
class LangController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'switch' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['switch'],
                'rules' => [
                    // allow authenticated users
                    [
                        'allow' => true,
                        // 'roles' => ['?', '*'],
                    ],
                    // everything else is denied
                ],
            ],
        ];
    }

    /**
     * Switches to a different language.
     * @return mixed
     */
    public function actionSwitch()
    {
        if (!Yii::$app->request->isAjax) {
            throw new BadRequestHttpException('Only AJAX request is allowed.');
        }

        Yii::info('LangController::actionSwitch():');

        $data = Yii::$app->request->post();
        Yii::info('  $data = '. print_r($data, true));

        $languageCode = $data['language'];
        Yii::info('  $languageCode = '. $languageCode);

        $oldLang = Yii::$app->language;

        $domains = Yii::$app->params['hello']['domains'];
        $newLang = $domains[$languageCode]['language'];

        // Yii::info('  $domains = '. print_r($domains, true));

        $redirect = $newLang !== $oldLang;

        $url = Yii::$app->request->referrer;
        Yii::info('  old $url = '. $url);

        if ($redirect) {
            $oldDomain = parse_url($url, PHP_URL_HOST);
            $newDomain = $domains[$languageCode]['domain'];
            $url = str_replace($oldDomain, $newDomain, $url);
        }

        Yii::info('  $oldLang = '. $oldLang);
        Yii::info('  $newLang = '. $newLang);
        Yii::info('  $redirect = '. $redirect);
        Yii::info('  new $url = '. $url);

        $session = Yii::$app->session;
        Yii::info('  $session->hasSessionId = ' . $session->hasSessionId);
        Yii::info('  $sessionID = ' . $session->id);

        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        return [
            'redirect' => $redirect,
            'url' => $url,
            'code' => 200,
        ];
    }
}

controllers/SampleController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Sample;
use app\models\SampleSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * SampleController implements the CRUD actions for Sample model.
 */
class SampleController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Sample models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new SampleSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Sample model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Sample model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Sample();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Sample model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Sample model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Sample model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Sample the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Sample::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

controllers/StatusLogController.php
<?php

namespace app\controllers;

use Yii;
use app\models\StatusLog;
use app\models\StatusLogSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * StatusLogController implements the CRUD actions for StatusLog model.
 */
class StatusLogController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all StatusLog models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new StatusLogSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single StatusLog model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new StatusLog model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new StatusLog();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing StatusLog model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing StatusLog model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the StatusLog model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return StatusLog the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = StatusLog::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::t('app', 'My Company'),
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    $navItems=[
        ['label' => Yii::t('app', 'Home'), 'url' => ['/site/index']],
        ['label' => Yii::t('app', 'Status'), 'url' => ['/status/index']],
        ['label' => Yii::t('app', 'Status Log'), 'url' => ['/status-log/index']],
        ['label' => Yii::t('app', 'Sample'), 'url' => ['/sample/index']],
        ['label' => Yii::t('app', 'About'), 'url' => ['/site/about']],
        ['label' => Yii::t('app', 'Contact'), 'url' => ['/site/contact']],
    ];
    if (Yii::$app->user->isGuest) {
        array_push(
            $navItems,
            ['label' => Yii::t('app', 'Sign In'), 'url' => ['/user/login']],
            ['label' => Yii::t('app', 'Sign Up'), 'url' => ['/user/register']]
        );
    } else {
        array_push($navItems,
            '<li>'
            . Html::beginForm(['/site/logout'], 'post')
            . Html::submitButton(
                Yii::t('app', 'Logout') . ' (' . Yii::$app->user->identity->username . ')',
                ['class' => 'btn btn-link logout']
            )
            . Html::endForm()
            . '</li>'
        );
    }
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => $navItems,
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <div class="container">
            <p class="pull-right">
                Language:
                <select id="language">
                    <?php
                        $domains = Yii::$app->params['hello']['domains'];
                        foreach ($domains as $key => $domain) {
                            echo '<option value="' . $key . '">' . $domain['name'] . '</option>';
                        }
                    ?>
                </select>
            </p>
        </div>
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
<script type="text/javascript">
$(function() {
    var switchLang = function(lang) {
        var csrfToken = $('meta[name="csrf-token"]').attr("content");
        $.ajax({
            url: '/lang/switch',
            type : 'POST',
            data: {language: lang, _csrf: csrfToken},
            success: function(data) {
                console.debug('/lang/switch success: data = ', data);

                if (data.redirect) {
                    window.location.href = data.url;
                }
            },
            error: function (jqXHR, textStatus, errorThrown){
                console.debug('/lang/switch error: ', errorThrown);
            },
            complete: function (jqXHR, textStatus){
                // console.debug('/lang/switch complete: textStatus = ', textStatus);
            }
        });
    }

    console.debug('language: <?php echo Yii::$app->language; ?>');
    console.debug('window.location: ', window.location);
    var currentLang = window.location.hostname.substring(0, 2);
    console.debug('currentLang: ', currentLang);
    $('#language').val(currentLang);

    $('#language').on('change', function(e) {
        e.preventDefault();
        var lang = this.value;
        console.debug('language selected: ', lang);
        // window.location.href = 'http://' + lang + window.location.href.substring(9);
        // window.location.href = '/lang/switch?language=' + lang;
        switchLang(lang);
    })
});
</script>
</body>
</html>
<?php $this->endPage() ?>